#!/bin/bash
#Get the necessary components
echo "deb http://ports.ubuntu.com/ubuntu-ports bionic-updates main restricted universe multiverse" >> /etc/apt/sources.list
echo "deb-src http://ports.ubuntu.com/ubuntu-ports bionic-updates main restricted universe multiverse" >> /etc/apt/sources.list
apt update
apt full-upgrade -y
apt autoremove
apt install lxde tigervnc-standalone-server tigervnc-common chromium-browser chromium-sandbox firefox libreoffice leafpad ibus ibus-m17n dbus-x11 sudo nano wget --no-install-recommends -y
#Setup the necessary files
mkdir ~/.vnc
wget https://raw.githubusercontent.com/MushfiqAziz/autobot/master/xstartup -P ~/.vnc/
wget https://raw.githubusercontent.com/MushfiqAziz/autobot/master/start-pc -P /usr/local/bin/
wget https://raw.githubusercontent.com/MushfiqAziz/autobot/master/stop-pc -P /usr/local/bin/
chmod +x ~/.vnc/xstartup
chmod +x /usr/local/bin/start-pc
chmod +x /usr/local/bin/stop-pc
echo "export DISPLAY=":0"" >> /etc/profile
source /etc/profile
rm /etc/xdg/autostart/lxpolkit.desktop  
mv /usr/bin/lxpolkit /usr/bin/lxpolkit.bak
rm lxde
mv /usr/local/bin/start-pc /usr/local/bin/von
mv /usr/local/bin/stop-pc /usr/local/bin/voff
